This project is working on Google Colab but keep in mind that this won't be the most performant solution.

## install dependancies, takes around 45 seconds


In [1]:
# Rendering Dependencies
!pip install gym pyvirtualdisplay > /dev/null 2>&1
!apt-get install -y xvfb python-opengl ffmpeg > /dev/null 2>&1
# Gym Dependencies
!apt-get update > /dev/null 2>&1
!apt-get install cmake > /dev/null 2>&1
!pip install --upgrade setuptools 2>&1
!pip install ez_setup > /dev/null 2>&1
!pip install gym[atari] > /dev/null 2>&1
!pip install gym[box2d] > /dev/null 2>&1
!pip install stable_baselines3

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.2 MB 31.1 MB/s 
  Attempting uninstall: setuptools
    Found existing installation: setuptools 57.4.0
    Uninstalling setuptools-57.4.0:
      Successfully uninstalled setuptools-57.4.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 177 kB 31.4 MB/s 
     |████████████████████████████████| 1.5 MB 59.2 MB/s 
  Created wheel for gym: filename=gym-0.21.0-py3-none-any.whl size=1616800 sha256=b0214e4877f280400074f3c1d6c05537b01b82aae47655c48f7c7c4551aa743e
  Stored in directory: /root/.cache/pip/wheels/76/ee/9c/36bfe3e079df99acf5ae57f4e3464ff2771b34447d6d2f2148
Successfully built gym
  Attempting uninstall: gym
    Found existing installation: gym 0.17.3
    Uninstalling gym-0.17.3:
      Successfully uninstalled gym-0.17.3


## Imports and Helper functions


In [63]:
import gym
from gym import logger as gymlogger
from gym.wrappers import Monitor
gymlogger.set_level(40) #error only
import tensorflow as tf
import numpy as np
import random
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline


In [3]:
#!pip install stable_baselines3

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
from stable_baselines3.common.policies import ActorCriticPolicy, ActorCriticCnnPolicy, MultiInputActorCriticPolicy
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3 import PPO

## Policy 1 ) PPO with ActorCriticPolicy

In [5]:
from stable_baselines3.common.policies import ActorCriticPolicy, ActorCriticCnnPolicy
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3 import PPO
env = gym.make(game)
model = PPO(ActorCriticPolicy, env, verbose=1)
model.learn(total_timesteps=10000)


Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.
Track generation: 1227..1538 -> 311-tiles track
Track generation: 1247..1565 -> 318-tiles track
Track generation: 1102..1382 -> 280-tiles track
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 1e+03    |
|    ep_rew_mean     | -61.7    |
| time/              |          |
|    fps             | 151      |
|    iterations      | 1        |
|    time_elapsed    | 13       |
|    total_timesteps | 2048     |
---------------------------------
Track generation: 1271..1593 -> 322-tiles track
Track generation: 1276..1599 -> 323-tiles track
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1e+03       |
|    ep_rew_mean          | -56.6       |
| time/                   |             |
|    fps                  | 145         |
|    iterations           | 2   

In [6]:
# Number of Dimensions in the Observable Space and number of Control Actions in the Environments
print('Observation Space:', env.observation_space)
print('Action Space:', env.action_space)

print("\n")
print("Observation Space Param: 96x96x3 values for Red, Green and Blue pixels")
print("Observation Space Highs:", np.mean(env.observation_space.high))
print("Observation Space Lows:   ", np.mean(env.observation_space.low))

Observation Space: Box([[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [2

In [7]:
obs = env.reset()
rewards_list = []
list = []
for i in range(1000):
    action, _states = model.predict(obs.copy())
    print(action)
    list.append(action)
    obs, rewards, dones, info = env.step(action)
    rewards_list.append(rewards)
    env.render()

Track generation: 1097..1376 -> 279-tiles track
[-0.3037467   0.6351942   0.22567363]
[-0.51548445  0.8662585   0.        ]
[0.349887  0.6699922 1.       ]
[-0.7485836   0.          0.01192026]
[1. 1. 0.]
[0.08302324 1.         0.        ]
[0.13869715 0.         0.3184814 ]
[-0.00972668  1.          0.        ]
[-1.          0.          0.11440544]
[-1.          0.03457487  0.        ]
[-1.  0.  0.]
[1. 1. 0.]
[-0.4758513   0.          0.36306536]
[-1.         0.5644481  0.       ]
[-0.05130921  1.          0.5705744 ]
[1.        0.6116456 0.       ]
[0.78928137 0.         1.        ]
[-0.25684166  0.          0.08788539]
[0.26986486 0.8484649  0.07682432]
[0.19415551 0.         0.        ]
[0.3558747 0.        0.       ]
[1.         0.71049464 0.        ]
[-0.9779016  0.         1.       ]
[0.747457   0.         0.22285001]
[-1.  1.  0.]
[0.34361467 0.         0.8005758 ]
[-0.6608821  0.4662683  0.       ]
[0.44135708 0.         0.        ]
[-1.  0.  0.]
[1. 0. 0.]
[-1.  0.  0.]
[0.27

In [17]:
import numpy as np
np.mean(rewards_list)

-0.02805755395683493

In [64]:
np.sum(rewards_list)

-28.05755395683493

## Policy 2) PPO with ActorCriticCNNPolicy

In [18]:

env = gym.make(game)
model = PPO(ActorCriticCnnPolicy, env, verbose=1)
model.learn(total_timesteps=10000)


Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.
Track generation: 1256..1574 -> 318-tiles track
Track generation: 1143..1433 -> 290-tiles track
Track generation: 1181..1487 -> 306-tiles track
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 1e+03    |
|    ep_rew_mean     | -58.6    |
| time/              |          |
|    fps             | 131      |
|    iterations      | 1        |
|    time_elapsed    | 15       |
|    total_timesteps | 2048     |
---------------------------------
Track generation: 1111..1393 -> 282-tiles track
Track generation: 1220..1529 -> 309-tiles track
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1e+03       |
|    ep_rew_mean          | -55.4       |
| time/                   |             |
|    fps                  | 130         |
|    iterations           | 2   

In [19]:
obs = env.reset()
rewards_list2 = []
list2 = []
for i in range(1000):
    action, _states = model.predict(obs.copy())
    print(action)
    list2.append(action)
    obs, rewards, dones, info = env.step(action)
    rewards_list2.append(rewards)
    env.render()

Track generation: 1074..1347 -> 273-tiles track
[-0.36566982  0.          0.7274541 ]
[1.        0.5174795 0.       ]
[1.         0.42467418 0.0053685 ]
[0.03433505 0.         0.00869033]
[1.        1.        0.6956474]
[0.24053386 0.93931085 0.8249234 ]
[-0.00686242  0.8335504   0.81131536]
[0.28338972 0.         0.        ]
[-1.  0.  0.]
[-0.41898093  1.          0.11081645]
[0.20637918 0.8856231  0.        ]
[-0.19963142  0.          0.9039713 ]
[-0.3756597   0.          0.63381433]
[-0.31333232  0.          0.        ]
[0.34477544 0.88106936 0.71035683]
[0.37545252 0.461061   0.        ]
[1.         0.80115694 1.        ]
[0.11269091 0.25070906 1.        ]
[-1.          1.          0.94841176]
[0.29713288 0.09664299 0.4350247 ]
[0.39534533 0.30023476 0.        ]
[-0.8667911  1.         1.       ]
[0.21946204 0.20587766 0.6930115 ]
[-0.6422613   1.          0.69514203]
[0.8592992 0.        1.       ]
[1.         0.         0.33205533]
[-0.4986763   0.          0.01780817]
[-1.  1.  

In [20]:
print(np.sum(rewards_list2))

-41.17647058823573


In [21]:
np.mean(rewards_list2)

-0.04117647058823573

## Policy 3) A2C with MLP Policy

In [22]:
from stable_baselines3 import A2C

env = gym.make(game)

model = A2C("MlpPolicy", env, verbose=1)

Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.


In [ ]:
obs = env.reset()
rewards_list3 = []
list3 = []
for i in range(1000):
    action, _states = model.predict(obs.copy())
    print(abs(action).max())
    list3.append(action)
    obs, rewards, dones, info = env.step(action)
    rewards_list3.append(rewards)
    env.render()

In [24]:
import numpy as np
np.mean(rewards_list3)

-0.0551724137931042

In [25]:
np.sum(rewards_list3)

-55.1724137931042

# EXTRA

## Let's make another environment to see our policies accuracy in a long run. 

In [27]:
from gym.envs.registration import make, register

register(
    id="Car_Racing-v99",
    entry_point="gym.envs.box2d.car_racing:CarRacing",
    max_episode_steps=2500,
    reward_threshold=2300.0,
)


In [28]:

env = gym.make("Car_Racing-v99")
model = PPO(ActorCriticPolicy, env, verbose=1)
model.learn(total_timesteps=10000)


Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.
Track generation: 1182..1480 -> 298-tiles track
-----------------------------
| time/              |      |
|    fps             | 160  |
|    iterations      | 1    |
|    time_elapsed    | 12   |
|    total_timesteps | 2048 |
-----------------------------
Track generation: 1231..1543 -> 312-tiles track
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 2.5e+03     |
|    ep_rew_mean          | -176        |
| time/                   |             |
|    fps                  | 144         |
|    iterations           | 2           |
|    time_elapsed         | 28          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.010311365 |
|    clip_fraction        | 0.132       |
|    clip_range           | 0.2         |
|    entropy

In [30]:
obs = env.reset()
rewards_list4 = []
list4 = []
for i in range(1000):
    action, _states = model.predict(obs.copy())
    print(action)
    list4.append(action)
    obs, rewards, dones, info = env.step(action)
    rewards_list4.append(rewards)
    env.render()

Track generation: 1068..1345 -> 277-tiles track
[-0.66569346  0.          0.044035  ]
[-0.6174582   0.08702757  0.07838308]
[1.       0.233749 0.      ]
[-1.          0.03679461  0.        ]
[-0.335855  0.        0.      ]
[0.8268221 0.        0.       ]
[-1.  0.  0.]
[-1.        0.545692  0.      ]
[-0.82931525  0.          0.        ]
[-1.  0.  0.]
[-1.          0.27253762  0.5699023 ]
[-0.49820292  0.          0.        ]
[-0.30450723  1.          0.        ]
[1.         0.46340132 0.        ]
[0.9365382 1.        0.       ]
[0.14359505 0.43504825 0.        ]
[-0.00901336  0.2898941   0.        ]
[1. 0. 0.]
[0.7428791 0.        0.       ]
[-0.4936695   0.72751755  0.        ]
[0.90714186 0.         0.        ]
[0.33011696 0.         0.07315692]
[1. 0. 0.]
[1.         0.20589465 0.        ]
[-0.03559315  0.          0.        ]
[1. 0. 0.]
[-1.          1.          0.14685807]
[-0.00056408  0.          0.        ]
[-1.          0.17910047  0.        ]
[-0.75866926  0.          0.     

In [33]:
import numpy as np
np.mean(rewards_list4)

-0.020289855072463715

In [32]:
import numpy as np
np.sum(rewards_list4)

-20.289855072463716

In [34]:
from stable_baselines3 import A2C

env = gym.make("Car_Racing-v99")

model = A2C("MlpPolicy", env, verbose=10)

Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.


In [35]:
obs = env.reset()
rewards_list5 = []
list5 = []
for i in range(1000):
    action, _states = model.predict(obs.copy())
    print(action)
    list5.append(action)
    obs, rewards, dones, info = env.step(action)
    rewards_list5.append(rewards)
    env.render()

Track generation: 1217..1530 -> 313-tiles track
[-1.          0.39012423  1.        ]
[-0.4681566  0.         0.       ]
[-0.5042066   0.18757947  0.        ]
[-0.5034206  0.         0.       ]
[-0.7601717  0.         0.       ]
[-0.8668415   1.          0.10053019]
[-1.          0.24537227  1.        ]
[0.04688038 0.         0.        ]
[0.7262532 0.        0.       ]
[-0.5716159  0.9576236  0.       ]
[1.         0.13052106 0.        ]
[-0.33405015  0.35954148  0.        ]
[1.        0.        0.7510605]
[1. 1. 0.]
[-0.33718586  0.5827556   0.        ]
[1.         0.11572056 0.        ]
[-0.2420223  0.         0.3182749]
[-1.          0.83030117  0.        ]
[0.27805194 0.         0.205777  ]
[1. 0. 0.]
[-0.8626741  0.9368742  1.       ]
[-1.          0.          0.78329986]
[-0.09478763  0.28911406  0.25515097]
[-0.37507978  0.          0.        ]
[-1.  0.  0.]
[0.14189038 0.         0.        ]
[-0.20416155  0.          0.92600906]
[-0.9371555  0.         1.       ]
[0.3032299  0.

In [36]:
np.sum(rewards_list5)

-51.92307692307769

In [37]:
np.mean(rewards_list5)

-0.05192307692307769

## Evaluation

In [44]:
reward_overall = [np.sum(rewards_list), np.sum(rewards_list2), np.sum(rewards_list3)]
policies = ["ActorCriticPolicy", "ActorCriticCNNPolicy", "MlpPolicy"]
algorithms = ["PPO", "PPO", "A2C"]

In [49]:
import pandas as pd

eval_df = pd.DataFrame()
eval_df["algorithm"] = algorithms
eval_df["policy"] = policies
eval_df["rewards"] = reward_overall

In [50]:
eval_df

algorithm                policy    rewards
0       PPO     ActorCriticPolicy -28.057554
1       PPO  ActorCriticCNNPolicy -41.176471
2       A2C             MlpPolicy -55.172414

It clearly shows that PPO algorithm has outperformed A2C. Why is that?

Because, PPO algorithm is actually an union of A2C (having multiple workers) and TRPO (it uses a trust region to improve the actor). The main idea is that after an update, the new policy should be not too far form the old policy. For that, PPO uses clipping to avoid too large update.
Therefore since our problem has 3 actional space, [x, x ,x] PPO has a better advantage!

For policies;

ActorCriticPolicy performs better than ActorCriticCNNPolicy in this problem. 
ActorCriticPolicy > Policy class for actor-critic algorithms (has both policy and value prediction)
CNN policy >  CNN policy class for actor-critic algorithms (has both policy and value prediction). Used by A2C, PPO and the likes.